--grinder recipes
local grindings = {
	{"basic_materials:carbon_steel_bar 2",          "technic:carbon_steel_dust"},
	{"boats:boat",                                  "technic:common_tree_grindings"},
	{"default:bookshelf",                           "technic:common_tree_grindings"},
	{"default:desert_sandstone_block",              "default:desert_sand 2"},
	{"default:desert_sandstone_brick",              "default:desert_sand 2"},
	{"stairs:slab_desert_sandstone",                "default:desert_sand"},
	{"stairs:slab_desert_sandstone_block",          "default:desert_sand"},
	{"stairs:slab_desert_sandstone_brick",          "default:desert_sand"},
	{"stairs:stair_desert_sandstone 2",             "default:desert_sand 3"},
	{"stairs:stair_desert_sandstone_block 2",       "default:desert_sand 3"},
	{"stairs:stair_desert_sandstone_brick 2",       "default:desert_sand 3"},
	{"stairs:stair_inner_desert_sandstone 4",       "default:desert_sand 7", 8},
	{"stairs:stair_inner_desert_sandstone_block 4", "default:desert_sand 7", 8},
	{"stairs:stair_inner_desert_sandstone_brick 4", "default:desert_sand 7", 8},
	{"stairs:stair_outer_desert_sandstone 4",       "default:desert_sand 5"},
	{"stairs:stair_outer_desert_sandstone_block 4", "default:desert_sand 5"},
	{"stairs:stair_outer_desert_sandstone_brick 4", "default:desert_sand 5"},
	{"basic_materials:cement_block 3",              "default:dirt"},
	{"basic_materials:gold_strip 6",                "technic:gold_dust"},
	{"stairs:slab_cobble 2",                        "default:gravel"},
	{"stairs:stair_cobble 4",                       "default:gravel 3"},
	{"stairs:stair_inner_cobble 8",                 "default:gravel 7", 8},
	{"stairs:stair_outer_cobble 8",                 "default:gravel 5"},
	{"basic_materials:lead_strip 6",                "technic:lead_dust"},
	{"default:obsidian",                            "default:obsidian_shard 9", 10},
	{"default:obsidian_block",                      "default:obsidian_shard 9", 10},
	{"default:obsidianbrick",                       "default:obsidian_shard 9", 10},
	{"default:obsidian_glass",                      "default:obsidian_shard"},
	{"default:sandstone_block",                     "default:sand 2"},
	{"default:sandstonebrick",                      "default:sand 2"},
	{"stairs:slab_sandstone",                       "default:sand"},
	{"stairs:slab_sandstone_block",                 "default:sand"},
	{"stairs:slab_sandstonebrick",                  "default:sand"},
	{"stairs:stair_sandstone 2",                    "default:sand 3"},
	{"stairs:stair_sandstone_block 2",              "default:sand 3"},
	{"stairs:stair_sandstonebrick 2",               "default:sand 3"},
	{"stairs:stair_inner_sandstone 4",              "default:sand 7", 8},
	{"stairs:stair_inner_sandstone_block 4",        "default:sand 7", 8},
	{"stairs:stair_inner_sandstonebrick 4",         "default:sand 7", 8},
	{"stairs:stair_outer_sandstone 4",              "default:sand 5"},
	{"stairs:stair_outer_sandstone_block 4",        "default:sand 5"},
	{"stairs:stair_outer_sandstonebrick 4",         "default:sand 5"},
	{"default:silver_sandstone_block",              "default:silver_sand 2"},
	{"default:silver_sandstone_brick",               "default:silver_sand 2"},
	{"stairs:slab_silver_sandstone",                "default:silver_sand"},
	{"stairs:slab_silver_sandstone_block",          "default:silver_sand"},
	{"stairs:slab_silver_sandstone_brick",          "default:silver_sand"},
	{"stairs:stair_silver_sandstone 2",             "default:silver_sand 3"},
	{"stairs:stair_silver_sandstone_block 2",       "default:silver_sand 3"},
	{"stairs:stair_silver_sandstone_brick 2",       "default:silver_sand 3"},
	{"stairs:stair_inner_silver_sandstone 4",       "default:silver_sand 7", 8},
	{"stairs:stair_inner_silver_sandstone_block 4", "default:silver_sand 7", 8},
	{"stairs:stair_inner_silver_sandstone_brick 4", "default:silver_sand 7", 8},
	{"stairs:stair_outer_silver_sandstone 4",       "default:silver_sand 5"},
	{"stairs:stair_outer_silver_sandstone_block 4", "default:silver_sand 5"},
	{"stairs:stair_outer_silver_sandstone_brick 4", "default:silver_sand 5"},
	{"basic_materials:stainless_steel_bar 2",       "technic:stainless_steel_dust"},
	{"basic_materials:stainless_steel_strip 6",     "technic:stainless_steel_dust"},
	{"default:furnace",                             "technic:stone_dust"},
	{"default:stone_block",                         "technic:stone_dust"},
	{"default:stonebrick",                          "technic:stone_dust"},
	{"stairs:slab_stone 2",                         "technic:stone_dust"},
	{"stairs:slab_stone_block 2",                   "technic:stone_dust"},
	{"stairs:slab_stonebrick 2",                    "technic:stone_dust"},
	{"stairs:stair_stone 4",                        "technic:stone_dust 3"},
	{"stairs:stair_stone_block 4",                  "technic:stone_dust 3"},
	{"stairs:stair_stonebrick 4",                   "technic:stone_dust 3"},
	{"stairs:stair_inner_stone 8",                  "technic:stone_dust 7", 8},
	{"stairs:stair_inner_stone_block 8",            "technic:stone_dust 7", 8},
	{"stairs:stair_inner_stonebrick 8",             "technic:stone_dust 7", 8},
	{"stairs:stair_outer_stone 8",                  "technic:stone_dust 5"},
	{"stairs:stair_outer_stone_block 8",            "technic:stone_dust 5"},
	{"stairs:stair_outer_stonebrick 8",             "technic:stone_dust 5"},
	{"bucket:bucket_empty",                         "technic:wrought_iron_dust 3"},
	{"doors:door_steel",                            "technic:wrought_iron_dust 6", 7},
	{"basic_materials:gear_steel 12",               "technic:wrought_iron_dust 9", 10},
	{"default:sign_wall_steel",                     "technic:wrought_iron_dust 2"},
	{"basic_materials:padlock 4",                   "technic:wrought_iron_dust 5"},
	{"basic_materials:steel_bar 2",                 "technic:wrought_iron_dust"},
	{"basic_materials:steel_strip 6",               "technic:wrought_iron_dust"},
	{"doors:trapdoor_steel",                        "technic:wrought_iron_dust 4"},
}

for _, data in pairs(grindings) do
	technic.register_grinder_recipe({input = {data[1]}, output = data[2], time = data[3] or 3})
end

--alloy recipes
local alloys = {
	{recipe = {"default:obsidian", "bucket:bucket_empty"}, output = "bucket:bucket_lava"},
	{recipe = {"default:obsidian_block", "bucket:bucket_empty"}, output = "bucket:bucket_lava"},
	{recipe = {"default:obsidianbrick", "bucket:bucket_empty"}, output = "bucket:bucket_lava"},
}

for _, i in pairs(alloys) do
	technic.register_alloy_recipe({input = i.recipe, output = i.output, time = i.time or 10})
end
